version: '3'

services:
  service1:
    image: jerryonimo/jenkinspipelinetest-service1:latest
    ports:
      - "8000:8000"
    networks:
      - my_network

networks:
  my_network:
    external: true
