version: '3'

services:
  service1:
    image: jerryonimo/jenkinspipelinetest-service1:latest
    ports:
      - "8001:8001"
    networks:
      - my_network

networks:
  my_network:
    external: true
